### ISSUE TITLE
¿Cómo puedo hacer para modificar el valor de las variables @headquarters y @terminal que se encuentran dentro de document?

### ISSUE THREAD

**Issue by es-daniel** [apokalipto/facturacr#1]
Necesito cambiar el valor de `@terminal`, sin embargo, no he encontrado la forma de pasar este valor por parámetro. Es posible pasar el valor por parámetro ?

**Comment by apokalipto** [comment]
Por el momento tiene que hacerlo explícito.
```ruby
invoice.terminal = "00002"
invoice.headquarters = "001"
```

**Comment by es-daniel** [comment]
Hacerlo explícito no me funcionó. Me lanza el siguiente error:  
`"#<NoMethodError: undefined method 'terminal=' for #<FE::Invoice:0x00007f825d5227b8>\nDid you mean?  terminal\n               serial=>"`

Sin embargo, basado en eso logré realizar un implementación de manera que puedo modificar las variables de instancia:

`invoice.instance_variable_set(:@terminal, '00002')`
`invoice.instance_variable_set(:@headquarters, '001')`

**Comment by apokalipto** [comment]
Cual version del gem esta usando?

**Comment by es-daniel** [comment]
Estoy utilizando la version 1.0.0

**Comment by apokalipto** [comment]
Use la version de master de git. Todavia no he hecho la actualizacion de
ese cambio en rubygems

**Comment by es-daniel** [comment]
Listo, con eso si me funcionó. Muchas gracias!
