### ISSUE TITLE
Habilidades del GEM

### ISSUE THREAD

**Issue by siba2893** [apokalipto/facturacr#6]
Buenas que tan complicado es implementar un sistema de facturacion digital en Rails utilizando esta gema para facturar. Que features hacen falta de ser implementados para poder hacer un sistema de facturacion completo para un POS por ejemplo?

**Comment by apokalipto** [comment]
Es relativamente sencillo. La librería ofrece toda la funcionalidad necesaria para crear los documntos electrónicos. No tiene la intención de funcionar como un sistema integral, sino más bien ser el componente que se encarga de la generación, firmado , envío y recepción de los documentos.

Voy a cerrar esto debido a que no es un "issue" de la librería.
